# GitHub Actionsはリポジトリ内の自動化されたワークフローを定義

name: generate caterpillar animation

on:
  # 実行スケジュール
  schedule:
    - cron: "0 4 * * 0" # 毎週日曜04時
  # 任意のタイミングで実行可能
  workflow_dispatch:
  # プッシュするたびに実行
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write # 書き込み権限
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps: # 処理内容
      # 芋虫を生成
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with: # アクションにパラメータを渡す
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./img/github-contribution-grid-snake.svg
            ./img/github-contribution-grid-snake-dark.svg?palette=github-dark
      # push
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with: # アクションにパラメータを渡す
          target_branch: caterpillar
          build_dir: ./img
        env:
          GITHUB_TOKEN: ${{ secrets.CATERPILLAR }}
      
          