# GitHub Actionsはリポジトリ内の自動化されたワークフローを定義

name: generate caterpillar animation

on:
  # 実行スケジュール
  schedule:
    - cron: "0 19 * * *" # 毎日04時に更新 "0 19 * * *"
  # 任意のタイミングで実行可能
  workflow_dispatch:

  # test
  # プッシュするたびに実行
  push:
    branches:
      - feature/github-profile-summary-cards_workflows

jobs:
  generate:
    permissions:
      contents: write # 書き込み権限
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps: # 処理内容
      # 芋虫を生成
      - name: generate snake.svg
        uses: Platane/snk@v3
        with: # アクションにパラメータを渡す
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./img/github-snake.svg
            ./img/github-snake-dark.svg?palette=github-dark
            ./img/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # push
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with: # アクションにパラメータを渡す
          target_branch: caterpillar
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.CATERPILLAR }}
      
          